name: Nightly Regression

on:
  schedule:
    # 03:00 UTC diariamente
    - cron: '0 3 * * *'
  workflow_dispatch:

env:
  CYPRESS_apiUrl: https://serverest.dev
  CYPRESS_frontUrl: https://front.serverest.dev

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run lint

  regression-api:
    name: Regression API
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - name: Run full API suite
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:api
      - name: Build HTML report
        if: always()
        run: npm run report:build
        continue-on-error: true
      - name: Upload regression API artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression-api-${{ github.run_id }}
          path: |
            cypress/reports/html
            cypress/reports/mochawesome
            cypress/screenshots
            cypress/videos
          if-no-files-found: ignore

  regression-frontend:
    name: Regression Frontend
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - name: Run full frontend suite
        uses: cypress-io/github-action@v6
        with:
          command: npm run test:frontend
      - name: Build HTML report
        if: always()
        run: npm run report:build
        continue-on-error: true
      - name: Upload regression frontend artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: regression-frontend-${{ github.run_id }}
          path: |
            cypress/reports/html
            cypress/reports/mochawesome
            cypress/screenshots
            cypress/videos
          if-no-files-found: ignore
